Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: surface
          AttributeType: S
        - AttributeName: analysis
          AttributeType: S
      KeySchema:
        - AttributeName: surface
          KeyType: HASH
        - AttributeName: analysis
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
